### ISSUE TITLE
build_all.sh fails

### ISSUE THREAD

**Issue by thesofakillers** [ReScience/MLRC#50]
Hi, I am running build_all.sh after successfully passing the check_yaml.py test suite and organizing my content. I am getting the following output:

```stdout
Building editorial/
/Users/thesofakillers/repos/MLRC/2021/editorial/journal
Rc files read:
  NONE
Latexmk: This is Latexmk, John Collins, 17 Mar. 2022. Version 4.77, version: 4.77.
No specific requests made, so using default for latexmk.
Latexmk: Doing main (small) clean up for 'article.tex'
Latexmk: Doing extra clean up (of final output files) for 'article.tex'
Latexmk: Doing main (small) clean up for 'content.tex'
Latexmk: Doing extra clean up (of final output files) for 'content.tex'
Latexmk: Doing main (small) clean up for 'header.tex'
Latexmk: Doing extra clean up (of final output files) for 'header.tex'
Latexmk: Doing main (small) clean up for 'metadata.tex'
Latexmk: Doing extra clean up (of final output files) for 'metadata.tex'
Latexmk: Missing bbl file 'article.bbl' in following:
 No file article.bbl.
make[1]: *** No rule to make target `article.bbl'.  Stop.
Build complete
Building togt2022badder/
/Users/thesofakillers/repos/MLRC/2021/togt2022badder/journal
Rc files read:
  NONE
Latexmk: This is Latexmk, John Collins, 17 Mar. 2022. Version 4.77, version: 4.77.
No specific requests made, so using default for latexmk.
Latexmk: Doing main (small) clean up for 'article.tex'
Latexmk: Doing extra clean up (of final output files) for 'article.tex'
Latexmk: Doing main (small) clean up for 'content.tex'
Latexmk: Doing extra clean up (of final output files) for 'content.tex'
Latexmk: Doing main (small) clean up for 'header.tex'
Latexmk: Doing extra clean up (of final output files) for 'header.tex'
rm: metadata.tex: No such file or directory
Traceback (most recent call last):
  File "/Users/thesofakillers/repos/MLRC/2021/togt2022badder/journal/./yaml-to-latex.py", line 93, in <module>
    content = generate_latex_metadata(filename_in, article)
  File "/Users/thesofakillers/repos/MLRC/2021/togt2022badder/journal/./yaml-to-latex.py", line 10, in generate_latex_metadata
    "% DO NOT EDIT - automatically generated from {filename}\n\n"
IndexError: list index out of range
make: *** [metadata.tex] Error 1
Build complete
rm: article.aux: No such file or directory
rm: article.bbl: No such file or directory
rm: article.blg: No such file or directory
rm: article.fdb_latexmk: No such file or directory
rm: article.fls: No such file or directory
rm: article.out: No such file or directory
rm: article.log: No such file or directory
rm: article.run.xml: No such file or directory
rm: article.bcf: No such file or directory
```

I am not sure what I should do about the missing `article.bbl` and the metadata.tex IndexError. Please let me know how I should debug this. Thank you

**Comment by koustuvsinha** [comment]
Hi @thesofakillers, can you please open the Pull Request with your state of the code? It will help us debug the issue. You can always continue to update the PR.

**Comment by thesofakillers** [comment]
Sure. I'll close this issue and do that.
